# @package _global_
defaults:
  - ../core/base_create@
  - _self_
  
splits: 
  - train
  - tuning
  - held_out

dataset: lab_correlated_MEDS_data_not_fused

paths: 
  input_dir: example_data/${dataset}
  output_dir: ${oc.env:BONSAI_PROCESSED_DATA}/${dataset}

exclude_regex: ^(?:D//).* # example regex to exclude all features that start with 'D'

numeric_column: "numeric_value_normalized"

tokenizer:
  vocabulary:
  cutoffs:
  sep_tokens: true
