# @package _global_
defaults:
  - /core/base_create@
  - _self_

dataset: correlated_MEDS_data

paths: 
  input_dir: example_data/${dataset}
  save_path: ${oc.env:BONSAI_PROCESSED_DATA}/${dataset}/outcomes/${hydra:job.config_name}.parquet

splits:
  - train
  - tuning
  - held_out

outcome:
  exclude: # OPTIONAL
    dependence: independent # independent/dependent
    conditions:
      - column: code
        value: [ D437 ]
        operator: startswith_any # in/startswith_any
      - column: code
        value: [ D438 ]
        operator: startswith_any # in/startswith_any

  outcome:
    dependence: independent # independent/dependent
    conditions:
      - column: code
        value: [ DE11 ]
        operator: startswith_any # in/startswith_any

  index:
    type: absolute # absolute/relative/exposure
    absolute_date: # absolute
      year: 2020
      month: 1
      day: 1
    relative_shift: # relative
    dependence: # exposure
    conditions: # exposure

  censor: # ALWAYS RELATIVE TO INDEX
    relative_shift: 
      hours: -1000 # 0 sets index=censor