defaults: 
  - core/base@
  - hardware/1gpu12cpu@hardware
  - _self_
  
checkpoint_path: /Users/zcr545/Desktop/Projects/repos/BONSAI/outputs/pretraining/config.json

model:
  ckpt_every_n_epoch: 1

data:
  split_idx: 1
  select_ratio: 1.
  masking_ratio: .8
  replace_ratio: .1
  ignore_special_tokens: true
  shuffle: true

training:
  batch_size: 128
  accumulate_grad_batches: 1 #previously called effective batch size
  epochs: 2
  learning_rate: 5e-4
  optimizer_epsilon: 1e-6
  sampling_weight_fn: 
    _target_: bonsai.functional.sampling.effective_n_samples
  loss_weight_function: 
    _target_: bonsai.functional.loss.effective_n_samples
  scheduler_warmup_epochs: 0.01 # DOUBLE CHECK THAT THIS IS DESIRED

  #Below is planned for implementation but not yet done
  #checkpoint_frequency: 1
  #early_stopping: 20 # rename this to tell what the value represents
  #stopping_criterion: roc_auc
  #n_layers_to_freeze: 1
  #unfreeze_on_plateau: true # unfreeze all layers if the performance is less than plateau_threshold 
  #unfreeze_at_epoch: 2 # if unfrezze_on_plateau is true, whichever condition is met first
  #plateau_threshold: 0.01 
  #reset_patience_after_unfreeze: true # reset early stopping counter after unfreezing

  # Below is not planned to be implemented
  #info: true
  #gradient_clip: 
  #  clip_value: 1.0

#model:
#  cls: default

