defaults: 
  - core/base_train@
  - hardware/cpu@hardware
  - _self_
  
 
dataset: correlated_MEDS_data

data:
  fold: 0
  dir: ${oc.env:BONSAI_PROCESSED_DATA}/${dataset}
  path_vocab: ${data.dir}/vocabulary.pt
  dataset_class: bonsai.modules.datasets.PretrainDataset.ARPretrainDataset


training:
  batch_size: 2
  accumulate_grad_batches: 2 #previously called effective batch size
  epochs: 5
  learning_rate: 5e-4
  optimizer_epsilon: 1e-6
  scheduler_warmup_epochs: 2
  limit_val_batches: 50
  limit_train_batches: 50
  ckpt_every_n_epoch: 1
  masking:
  max_len: 10
  cutoff_date:
    day: 1
    month: 1
    year: 2015
    
model:
  hidden_size: 64
  num_hidden_layers: 2
  num_attention_heads: 2
  intermediate_size: 32
  type_vocab_size: 256
  embedding_dropout: 0.1 
  max_position_embeddings: 128
  age_scale: 1e-2 # 100 -> 1
  abspos_scale: 1e-5 # 400k -> 4
  age_shift: -50 # center around 0
  abspos_shift: -90_000 # 0 will be around 2015
  is_causal: false  
  