defaults:
  - core/base_create@
  - _self_
  
splits: 
  - train
  - tuning
  - held_out

dataset: 

paths: 
  input_dir: example_data/${dataset}
  output_dir: ${oc.env:BONSAI_PROCESSED_DATA}/${dataset}

exclude_regex: 

tokenizer:
  vocabulary:
  cutoffs:
  sep_tokens: true
