defaults:
  - core/base_create@
  - _self_

dataset: 

data:  
  input_dir: example_data/${dataset}
  save_path: ${oc.env:BONSAI_PROCESSED_DATA}/${dataset}/outcomes/${hydra:job.config_name}.parquet

splits:
  - train
  - tuning
  - held_out

outcome:
  exclude: # OPTIONAL
    dependence: independent #or dependent
    conditions:
      - col: code
        vals: [ D437 ]
      - col: code
        vals: [ D438 ]
  match:
    dependence: independent #or dependent
    conditions:
      - col: code
        vals: [ DE11 ]

  index:
    type: absolute # or relative
    date:
      year: 2020
      month: 1
      day: 1

  censor:
    type: relative # or absolute
    hour_shift: -1000
