splits: 
  - train
  - tuning
  - held_out

path_data: example_data/correlated_MEDS_data
path_tokenized: ${oc.env:BONSAI_PROCESSED_DATA}/${hydra:job.config_name}

exclude_regex: ^(?:LAB).* # example regex to exclude all features that start with 'LAB'

tokenizer_kwargs:
  sep_tokens: true
