# @package _global_
defaults: 
  - ../finetune@
  - ../hardware/cpu@hardware
  - _self_


paths:
  population: ${paths.dir}/diabetes_cohort.csv

labels:
  # we will convert outcomes to binary based on whether at least one outcome is in the follow up window
  n_hours_start_include: 168 # start follow up (considering outcomes) time after index date (negative means before)
  n_hours_end_include: 8760
