# @package _global_
defaults:
  - /core/base_create@
  - _self_

dataset: phair_light

paths: 
  input_dir: FILL_OUT_THIS/${dataset}
  save_path: ${oc.env:BONSAI_PROCESSED_DATA}/${dataset}/outcomes/${hydra:job.config_name}.parquet

splits:
  - train
  - tuning
  - held_out

outcome:
  exclude: # OPTIONAL
    dependence: independent # independent/dependent
    conditions:
      - col: code
        vals: [ DIAGNOSIS//DE160, DIAGNOSIS//DE161, DIAGNOSIS//DE162 ]
        match: prefix # exact/prefix
  outcome:
    dependence: independent # independent/dependent
    conditions:
      - col: code
        vals: [ DIAGNOSIS//DE160, DIAGNOSIS//DE161, DIAGNOSIS//DE162 ]
        match: prefix # exact/prefix

  index:
    type: exposure # absolute/relative/exposure
    dependence: independent # exposure
    conditions: 
      - col: code
        vals: [ MEDICATION//MA10BB ]
        match: prefix # exact/prefix

  censor: # ALWAYS RELATIVE TO INDEX
    relative_shift: 0 # 0 sets index=censor