hydra:
  verbose: false
  output_subdir: hydra
  run:
    dir: ${oc.env:BONSAI_MODELS}/${dataset}/${hydra:job.config_name}
  sweep:
    dir: ${oc.env:BONSAI_MODELS}/${dataset}
    subdir: ${hydra:job.config_name}
