hydra:
  verbose: false
  output_subdir: hydra
  run:
    dir: ${oc.env:BONSAI_MODELS}/${hydra:job.config_name}/${data.fold}
  sweep:
    dir: ${oc.env:BONSAI_MODELS}
    subdir: ${hydra:job.config_name}/${data.fold}
