defaults:
  - core/base_create@
  - _self_

dataset:

patient_table:

mapping_file:

paths: 
  input_dir: ${dataset}/data
  patient_table: ${patient_table}
  mapping_file: ${mapping_file}
  save_path: ${oc.env:BONSAI_PROCESSED_DATA}/${dataset}/outcomes/${hydra:job.config_name}.parquet

splits:
  - train
  - test

outcome: # defining outcomes based on the patient table
  outcome: 
    date: pregnancy_end
    conditions: 
      - col: GA_days
        operator: "<"
        value: 259

  index: GA_140_date
  censor: # relative to index
    relative_hour_shift: 0 # 0 sets index=censor