defaults: 
  - examples/example_finetune
  - _self_

dataset:
outcome:
pretrain_path:

labels:
  prediction_horizons: [3, 6, 12, 24, 32] # in months
  end_of_followup: 
    year: 2024
    month: 1
    day: 1

training:
  sampling_weight_fn: null
  loss_weight_function: null