name: 'Pipeline test'

on:
    workflow_dispatch:
    pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  BONSAI_CONFIG_PATH: "./configs"

jobs:
    pipeline_tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip' 

            - name: Install Dependencies
              run: |
                pip install .[dev]

            - name: Set working directory
              run: echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
              working-directory: ${{ github.workspace }}
          
            - name: test
              run: |
                echo $ls
                
            - name: create_data
              run: |
                HYDRA_FULL_ERROR=1 python bonsai/run/create_data.py --config-name example_data dataset=correlated_MEDS_data

            - name: pretrain
              run: |
                python bonsai/run/pretrain.py --config-name pretrain dataset=correlated_MEDS_data

            - name: create_outcome
              run: |
                python bonsai/run/create_outcome.py --config-name example_outcome1 dataset=correlated_MEDS_data

            - name: train (no pretrain path)
              run: |
                python bonsai/run/train.py --config-name finetune dataset=correlated_MEDS_data outcome=example_outcome1
